### ISSUE TITLE
Primeiros Passos: Estrutura do Projeto.

### ISSUE THREAD

**Issue by danielhe4rt** [he4rt/sinergicon-landing#1]
Estamos liberando esse novo projeto que já está parado há algum tempo, porém nós acreditamos muito que os detentores do projeto deveriam escolher a stack e como ele vai ser mantido.

Após dizer isso gostaria de ressaltar algumas coisas:  nós damos preferência pra projetos que são simples de manter, tanto com complexidade quanto com frameworks pois a He4rt é um lugar para iniciantes poderem se localizar.

Pra esse projeto começar, precisamos de:

- [x] #14
- [x] #13
- [x] README bem explicativo sobre o projeto e como se localizar
- [x] Como contribuir
- [x] #9

O link do figma do projeto é esse: [Sinergicon Figma](https://www.figma.com/file/0sEUG7JV543jYNhMnr9wHJ/Sinergicon?node-id=2%3A3&t=EuhKPChoQwOqIGe4-1)

Acreditamos que todas as discussões deverão ser feitas via issue, pra fomentar o Open Source em si e mostrar para desenvolvedores iniciantes que tudo é um DEBATE filosófico até chegar em uma implementação concreta.

Tem mais algo que podemos agregar aqui?

**Comment by HenriqueBros** [comment]
Muito massa primo, disposto a ajudar com oque for possivel.

**Comment by w1lldantas** [comment]
Concordo com pontos @DanielHe4rt 

Caso as tecnologias forem de domínio meu (JS || TS), creio que possa ajudar na construção do projeto. Mas antes de qualquer definição de tecnologias, este projeto é para ser uma landing page e temos o interesse de servir como pwa? 

Sugiro como processador utilizarmos o [vite](https://vitejs.dev/guide/) (a menos que fomos usar o angular, que ai não tem como 😢) que aponta alguns [soluções](https://vitejs.dev/guide/why.html) de problemas em comparação aos outros.

**Comment by rheronides** [comment]
@RikoKami , tem algum motivo específico para a sugestão do vite?
A princípio na discussão da live, nós havíamos definido seguir pelo angular. Mas isso apenas por preferência tecnologia pessoal.
Estou aberto a ser contrariado e fomentar a discussão do vite.

**Comment by w1lldantas** [comment]
@rheronides Me recordo na live de sugerimos tecnologias no chat, entretanto não me pareceu definido.

Entendo sua sugestão por preferência, eu já estou querendo sair um pouco da zona de conforto, por isso sou a favor de usarmos o Angular 😅

Minha sugestão do vite foi caso não for feito em Angular, poderíamos utiliza-lo com vue, preact ou react. Além de alguns outros fatores como: compilação sob demanda, configuração zero para vários pre-processadores prontos pra uso (o que entra no ponto de ser simples e fácil entendimento), typescript / jsx por esbuild que deixa bem rápido... enfim, tem vários comparativos por aí relacionados a vite vs webpack/snowpack/cra.

**Comment by danielhe4rt** [comment]
E ai galera bonita, tivemos algum andamento?

**Comment by w1lldantas** [comment]
Vou criar uma estrutura de readme e de como contribuir em pt-br, enquanto não foram decidido a linguagem.

Se for em react, eu posso criar o boiilerplate. Se for em angular, o boilerplate irá ser mais demorado, pois não conheço o framework.

**Comment by LeonardoRafaelDev** [comment]
Não curto usar um bazuca pra em projeto que não precisa tanto que nem uma landing simples, creio que usar, vite js vanilla e algum framework como tailwind ja esta de bom tamanho, para os sliders da para usar swiper, a unica questão e se vai ser pwa ou ssr.

em via de duvidas da pra burlar isto como o https://astro.build/

que da pra buildar ssr (creio que uma grande rota de curva dificultando, mas prefiro a ideia de deixar algo simples como próprio js vanilla, para outros pessoas iniciantes conseguirem contribuir, alias seria so html css

projeto ex: https://github.com/he4rt/he4rt-landing

**Comment by w1lldantas** [comment]
Gostaria de usar um framework para utilizar libs css-in-js. É algo simples de usar e fácil, além de qlqr um que pegue, vai poder dizer que tem experiência com, além de que o conceito é igual de css só muda a forma de escrita.

Aparentemente o [stitches ](https://stitches.dev/docs/framework-agnostic) é independente, o que nos dá a possibilidade de ser sem um framework.

Por mais que premissa de ser "iniciantes conseguirem contribuir", react é um dos mais fáceis. Mas ok.

Podemos ter como tecnologias utilizadas:
- [x] Vanilla com Typescript
- [x] Vite
- [x] [Stitches](https://stitches.dev/)

Projetos pequenos e com typescript é ótimo para aprendizagem.

Estou montando um boilerplate pra mim aqui, caso for decidido dessa forma. @LeonardoRafaelDev

**Comment by w1lldantas** [comment]
Por força no hábito, rodei o script de enviar tudo pra branch em que eu estava. 🤡  
Como é apenas um único commit, é pequeno e passível de ajuste em futuras branches. Vou mapear o que falta alterar e lhe informo ✌️ @LeonardoRafaelDev

**Comment by LeonardoRafaelDev** [comment]
concordo com a ideia da @RikoKami, boilerplate ja esta ok @DanielHe4rt, irei criar as issues com as seçoes que tens a ser desenvolvidas.

**Comment by danielhe4rt** [comment]
Só levantar um README.md simples antes de começar o projeto e ai sim pode dalhe.

**Comment by LeonardoRafaelDev** [comment]
por conta do projeto ter ficado parado eu e o @thel3onardo iremos refaze-lo em outra stack para a entregar ser mais rapida.
Irei criar as issues das tecnologias e boilerplate

**Comment by LeonardoRafaelDev** [comment]
Cogitamos usar astro + tailwind por conta do design do projeto ja ser "inspirado" e para ser de facil contribuição visto que estara em vanilla html js. precisando levantar boilerplate que sera feito hoje pelo @thel3onardo

**Comment by LeonardoRafaelDev** [comment]
Landing page ate então pronta
podendo ser revisado pequenos detalhes passado e refatoração melhores <3
obrigado @thel3onardo por encarar tudo cmg tmj lek 
@DanielHe4rt sobe pro teu pai

**Comment by LeonardoRafaelDev** [comment]
Save 
![Captura de Tela 2024-08-04 às 17 11 01](https://github.com/user-attachments/assets/5841507d-8f5b-4b2d-939b-ca4f3945bf62)

Recebemos alguma alteraçoes a serem feitas pela parte da sinergicon e irei criar outra issue principal para o projeto e irei finalizar essa <3
