### ISSUE TITLE
Section Venha conhecer os nossos serviços 

### ISSUE THREAD

**Issue by LeonardoRafaelDev** [he4rt/sinergicon-landing#3]
![image](https://user-images.githubusercontent.com/65264908/213305010-458d95a9-7877-4787-b747-abddaee78823.png)

### Figma:  https://www.figma.com/file/0sEUG7JV543jYNhMnr9wHJ/Sinergicon?node-id=2%3A3&t=OQXal3NweJ4vwGt2-0

**Comment by thel3onardo** [comment]
Fico com essa parte do site
