### ISSUE TITLE
Section Footer/Contacts

### ISSUE THREAD

**Issue by LeonardoRafaelDev** [he4rt/sinergicon-landing#7]
![image](https://user-images.githubusercontent.com/65264908/213305827-9fb6053c-0e83-4b21-b841-e78f938e7c53.png)

### Figma:  https://www.figma.com/file/0sEUG7JV543jYNhMnr9wHJ/Sinergicon?node-id=2%3A3&t=OQXal3NweJ4vwGt2-0

**Comment by LeonardoRafaelDev** [comment]
@DanielHe4rt nesta seção o form tera que ter alguma validação visual no front-end?
como por exemplo input ficando vermelho não encontrei nada referente a isto no figma

**Comment by thel3onardo** [comment]
Fico com essa parte do site
